Import('*')

if env['x11']:
    SConscript('x11/SConscript')

if env['dri']:
    SConscript([
        'dri/common/xmlpool/SConscript',
        'dri/common/SConscript',
        'dri/i915/SConscript',
        'dri/i965/SConscript',
        'dri/radeon/SConscript',
        'dri/r200/SConscript',
    ])
